"""Internal error code constants for the provisioning API (not HTTP status codes)."""


class ErrorCode:
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTH_ERROR = "AUTH_ERROR"
    SITE_NOT_FOUND = "SITE_NOT_FOUND"
    SITE_CONFIG_MISSING = "SITE_CONFIG_MISSING"
    SITE_CONFIG_INVALID = "SITE_CONFIG_INVALID"
    INTERNAL_ERROR = "INTERNAL_ERROR"
